added tests for shopping cart functionality
annton-shakur/online-book-store-project pull request #14
Opened 2024-01-10 10:42 UTC by annton-shakur

2024-01-11 11:56 UTC, yevheniisynytsia requested changes
Well done! Only small changes requested

2024-01-11 11:56 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstoreproject/repository/ShoppingCartRepositoryTest.java
> +        assertEquals(Set.of(cartItem), actual.getCartItems());
TBH comparing shopping carts is enough, but you can leave as it is also

2024-01-11 11:56 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstoreproject/service/impl/ShoppingCartServiceImplTest.java
> +    private static User user;
place those before mocks

2024-01-11 11:56 UTC, yevheniisynytsia commented on src/test/java/mate/academy/onlinebookstoreproject/service/impl/ShoppingCartServiceImplTest.java
> +        Mockito.when(shoppingCartMapper.toDto(shoppingCart))
please add static import

2024-01-11 11:56 UTC, yevheniisynytsia commented on src/test/resources/database/cart-items/delete-cart-items.sql
> +DELETE FROM cart_items
add empty lines

2024-01-11 17:14 UTC, annton-shakur commented on src/test/java/mate/academy/onlinebookstoreproject/repository/ShoppingCartRepositoryTest.java
> +        assertEquals(Set.of(cartItem), actual.getCartItems());
i added this for testing whether cart items are fetched additionally

2024-01-12 07:26 UTC, yevheniisynytsia approved these changes

2024-01-12 10:20 UTC, merged