feat: added readme file
annton-shakur/online-book-store-project pull request #15
Opened 2024-01-11 07:13 UTC by annton-shakur

2024-01-11 08:58 UTC, d1sam requested changes
Good job, but there are some improvements should be done!

2024-01-11 08:58 UTC, d1sam commented on readme.md
> +## Technologies used
it's better to split technologies to categories.

2024-01-11 08:58 UTC, d1sam commented on readme.md
what about sections:
- Elaborate on how someone can set up or use your project. This is a very important part.
- Don't forget to mention any challenges you faced and how you overcame them.
- Possible improvements.

2024-01-12 07:30 UTC, yevheniisynytsia approved these changes
I like your readme - great job!

2024-01-12 07:30 UTC, yevheniisynytsia commented on readme.md
> +* You are welcome to try out this application options using the next Postman collection: there will be a collection here tomorrow (I hope). Just let me know if the other steps are valid
please do not forget to add it
it is important for local testing

2024-01-12 10:24 UTC, merged