implemented jwt authentication
annton-shakur/online-book-store-project pull request #8
Opened 2023-12-26 06:45 UTC by annton-shakur

2023-12-26 14:06 UTC, andrii-hoienko requested changes

2023-12-26 14:06 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstoreproject/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
Please add @Valid annotation to apply validation rules

2023-12-26 14:06 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstoreproject/dto/user/UserLoginRequestDto.java
> +public record UserLoginRequestDto(
Is it ok if email and password is string like "            "?

2023-12-26 14:06 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstoreproject/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Please don`t forget about constants

2023-12-26 14:06 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstoreproject/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 14:06 UTC, andrii-hoienko commented on src/main/java/mate/academy/onlinebookstoreproject/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-27 11:15 UTC, d1sam approved these changes
Well done!

2023-12-27 14:23 UTC, merged