Added category model support with corresponding services and entities
annton-shakur/online-book-store-project pull request #9
Opened 2023-12-28 18:07 UTC by annton-shakur

2023-12-28 21:35 UTC, MinoDentori approved these changes
Looks good to me.

2023-12-29 08:01 UTC, d1sam requested changes
good job, but some changes should be done!

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/controller/CategoryController.java
> +    @PostMapping
```suggestion
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/controller/CategoryController.java
> +    @DeleteMapping("/{id}")
```suggestion
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @DeleteMapping("/{id}")
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
exclude from `equals/hashCode` and `toString`.

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/model/Category.java
> +@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```suggestion
@NoArgsConstructor
@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/mapper/BookMapper.java
> +    }
```suggestion
    default void setCategories(@MappingTarget Book book, 
    CreateBookRequestDto bookDto) {
    book.setCategories(bookDto.getCategoryIds().stream()
      .map(Category::new)
      .collect(Collectors.toSet()));
     }
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/service/impl/BookServiceImpl.java
> +    }
```suggestion
```

2023-12-29 08:01 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstoreproject/service/impl/BookServiceImpl.java
> +        setCategories(requestDto, book);
```
 @Override
  public BookDto update(Long bookId, CreateBookRequestDto bookDto) {
    if (!bookRepository.existsById(bookId)) {
      throw new EntityNotFoundException("Can't found book with id: " + bookId);
    }
    Book book = bookMapper.toModel(bookDto);
    book.setId(bookId);
    Book updatedBook = bookRepository.save(book);
    return bookMapper.toDto(updatedBook);
  }
```

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-create-users-roles-table.yaml
>                      primaryKey: true
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/05-create-users-roles-table.yaml
>                      primaryKey: true
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +      author: anton4uk
```suggestion
      author: anton dudar
```

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +      author: anton4uk
```suggestion
      author: anton dudar
```

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 13:41 UTC, vovasalyha approved these changes

2024-01-02 12:20 UTC, merged